name: dsx
description: DSX Application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  global_configuration: ^1.4.0
  flutter_secure_storage: ^3.3.1
  json_annotation: ^2.0.0
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/login_logo.png
    - assets/cfg/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: AdventProSemiBold
      fonts:
        - asset: assets/fonts/Advent_Pro/AdventPro-SemiBold.ttf

